# Generated by Django 5.2 on 2026-04-25 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payouts.payout'),
        ),
    ]
